### PR TITLE
Updates for webpack 2+ and react 15+

### PR DESCRIPTION
**Pull request by jcgertig**

### CODE REVIEW

**Comment by jcgertig** [comment]
@Radivarig please review as soon as possible

**Comment by jcgertig** [comment]
@Radivarig any thoughts or criticisms?

**Comment by jcgertig** [comment]
@Radivarig if you would like you can also give me publish access with `npm owner add jcgertig`

**Comment by Radivarig** [comment]
@jcgertig Thank you for the PR, I'm reading trough the diff and will comment

**Comment by jcgertig** [comment]
Ahh my bad I went ahead and merged. I can revert if needed. The base of what I did was reorganize for npm moved the code that's not needed in the package to the test folder and npm ignored it. Also moved to react 15 and the separation of prop-types will be completely removed from react in 16.x. Also added a full build so that the code in the package itself is already built and does not force babel-loader. Also since react-dom was only needed in the test it reduces the number of peer-dependencies so its easier to keep up to date.

**Comment by jcgertig** [comment]
Created a revert branch if you feel its needed

**Comment by Radivarig** [comment]
It's ok. Added you to npm. Installed and tested. Thanks for your contribution!

**Pull request merged**
